apiVersion: apps/v1
kind: Deployment
metadata:
  name: tba-activemq
spec:
  selector:
    matchLabels:
      app: tba-activemq
  replicas: 1
  template:
    metadata:
      labels:
        app: tba-activemq
    spec:
      containers:
      - image: nexus.daf.teamdigitale.it/tba-activemq.5.15.1:1.1.0
        name: tba-activemq
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
        - containerPort: 61616
        - containerPort: 8161
        - containerPort: 5672
        - containerPort: 61613
        - containerPort: 1883
        - containerPort: 61614
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/activemq/data
          subPath: tba/evergreen2/activemq/data
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      nodeSelector:
        nifi: "true"
