apiVersion: apps/v1
kind: Deployment
metadata:
  name: tba-kylo-ui
spec:
  selector:
    matchLabels:
      app: tba-kylo-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: tba-kylo-ui
    spec:
      hostNetwork: false #changed by Fabio from true
      # dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nexus.daf.teamdigitale.it/tba-kylo-ui.8.4:1.1.0
        name: tba-kylo-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8400
        volumeMounts:
        - mountPath: /opt/kylo/kylo-ui/conf
          name: kylo-ui-config
        - mountPath: /var/log/kylo-ui
          subPath: tba/evergreen2/kylo-ui/log
          name: glusterfsvol
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: kylo-ui-config
        configMap:
          name: kylo-ui
      nodeSelector:
        nifi: "true"
