apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tba-kylo-services
  name: tba-kylo-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tba-kylo-services
    spec:
      containers:
      - image: 10.98.74.120:5000/tba-kylo-services.8.3.3:1.0.0-SNAPSHOT
        name: tba-kylo-services
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8420
        resources: {}
        volumeMounts:
        - mountPath: /opt/kylo/kylo-services/conf
          name: kylo-services-config
        - mountPath: /var/log/kylo-services
          name: tba-kylo-services-logs
        - mountPath: /etc/hadoop/conf
          name: hadoop-config
      restartPolicy: Always
      volumes:
      - name: tba-kylo-services-logs
        persistentVolumeClaim:
          claimName: tba-kylo-services-logs
      - name: kylo-services-config
        configMap:
          name: kylo-services
      - name: hadoop-config
        configMap:
          name: hadoop-config
      imagePullSecrets:
      - name: regsecret
status: {}
