apiVersion: apps/v1
kind: Deployment
metadata:
  name: tba-mysql
spec:
  selector:
    matchLabels:
      app: tba-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: tba-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: hadoop
        image: nexus.daf.teamdigitale.it/tba-mysql.10.3:1.1.0
        name: tba-mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: glusterfsvol
          mountPath: /var/lib/mysql
          subPath: tba/evergreen2/mysql/data
          readOnly: false
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      nodeSelector:
        nifi: "true"
