apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tba-kylo-ui
  name: tba-kylo-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tba-kylo-ui
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nexus.teamdigitale.test/tba-kylo-ui.8.4:1.0.2-SNAPSHOT
        name: tba-kylo-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8400
        resources: {}
        volumeMounts:
        - mountPath: /opt/kylo/kylo-ui/conf
          name: kylo-ui-config
        - mountPath: /var/log/kylo-ui
          subPath: tba/evergreen2/kylo-ui/log
          name: glusterfsvol
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: kylo-ui-config
        configMap:
          name: kylo-ui
      imagePullSecrets:
      - name: regsecret
status: {}
