apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tba-kylo-ui0-9-1
  name: tba-kylo-ui0-9-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tba-kylo-ui0-9-1
        nifi: "true"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nexus.teamdigitale.test/tba-kylo-ui.9.1:1.1.0
        name: tba-kylo-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8401
        resources:
          limits:
            memory: 2096Mi
        volumeMounts:
        - mountPath: /opt/kylo/kylo-ui/conf
          name: kylo-ui-config0-9-1
        - mountPath: /var/log/kylo-ui
          subPath: tba/evergreen2/kylo-ui/log
          name: glusterfsvol
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: kylo-ui-config0-9-1
        configMap:
          name: kylo-ui0-9-1
      imagePullSecrets:
      - name: regsecret
      nodeSelector:
        nifi: "true"
status: {}
