apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tba-kylo-services
  name: tba-kylo-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tba-kylo-services
        nifi-cluster: "true"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
      - ip: "192.168.20.20"
        hostnames:
        - "elk-master-1.teamdigitale.test"
        - "elk-master-1"
      containers:
      - image: nexus.teamdigitale.test/tba-kylo-services.9.1:3.0.0
        name: tba-kylo-services
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8420
        resources:
          limits:
            memory: 9096Mi
        volumeMounts:
        - mountPath: /opt/kylo/kylo-services/conf
          name: kylo-services-config
        - name: glusterfsvol
          mountPath: /var/log/kylo-services
          subPath: tba/evergreen2/kylo-services/log
        - name: glusterfsvol
          mountPath: /etc/security/
          subPath: tba/security/
          readOnly: true
        - name: sparkhome
          mountPath: /opt/cloudera/parcels/
          readOnly: true
        - name: sparkconf
          mountPath: /etc/spark2/
          readOnly: true
        - name: spark1conf
          mountPath: /etc/spark/
          readOnly: true
        - name: alternatives
          mountPath: /etc/alternatives/
          readOnly: true
        - name: hosts
          mountPath: /etc/extra_hosts
          readOnly: true
        - name: krb5conf
          mountPath: /etc/krb5.conf
          readOnly: true
        - name: hadoop
          mountPath: /etc/hadoop
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: kylo-services-config
        configMap:
          name: kylo-services
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoop
        hostPath:
          path: /etc/hadoop
      - name: sparkhome
        hostPath:
          path: /opt/cloudera/parcels/
      - name: alternatives
        hostPath:
          path: /etc/alternatives/
      - name: spark1conf
        hostPath:
          path: /etc/spark/
      - name: sparkconf
        hostPath:
          path: /etc/spark2/
      imagePullSecrets:
      - name: regsecret
      nodeSelector:
        nifi: "true"
status: {}
