apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tba-mysql
  name: tba-mysql
spec:
  type: "NodePort"
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: tba-mysql
status:
  loadBalancer: {}
