apiVersion: v1
kind: Service
metadata:
  labels:
    app: tba-nifi
  name: tba-nifi
spec:
  type: "NodePort"
  ports:
  - name: "8033"
    port: 8033
    targetPort: 8033
    nodePort: 31083
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 31081
  selector:
    app: tba-nifi
status:
  loadBalancer: {}
