apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  # selector:
  #   matchLabels:
  #     type: activemq-data
