apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tba-elasticsearch-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  # selector:
  #   matchLabels:
  #     type: esdata
