apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tba-kylo-services-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
