apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  # selector:
  #   matchLabels:
  #     type: nifi-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  # selector:
  #   matchLabels:
  #     type: nifi-logs
