apiVersion: v1
kind: PersistentVolume
metadata:
  name: tba-activemq
  labels:
    type: activemq-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tba/data/activemq
