apiVersion: v1
kind: PersistentVolume
metadata:
  name: tba-kylo-ui-logs
  labels:
    type: tba-kylo-ui-logs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tba/data/kylo-ui/logs
