apiVersion: v1
kind: PersistentVolume
metadata:
  name: tba-mysql
  labels:
    type: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql
