apiVersion: v1
kind: Service
metadata:
  labels:
    app: { tba-kylo-services-app }
  name: { tba-kylo-services-name }
spec:
  type: "NodePort"
  ports:
  - name: "8420"
    port: 8420
    targetPort: 8420
    nodePort: 30470
  - name: "8450"
    port: 8450
    targetPort: 8450
    nodePort: 30479
  - name: "8451"
    port: 8451
    targetPort: 8451
    nodePort: 30473
  selector:
    app: { tba-kylo-services-app }
status:
  loadBalancer: {}