apiVersion: v1
kind: Service
metadata:
  labels:
    app: { tba-mysql-app }
  name: { tba-mysql-name }
spec:
  type: "NodePort"
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: { tba-mysql-app }
status:
  loadBalancer: {}
