apiVersion: v1
kind: Service
metadata:
 name: { tba-nifi-name }
 labels:
   app: { tba-nifi-app }
spec:
 selector:
   app: { tba-nifi-app }
 clusterIP: None   #headless
 ports:
 ports:
 - name: "nifi-http"
   port: 8080
 - name: "listerner"
   port: 8033
 - name: "nifi-input"
   port: 9998
 - name: "nifi-cluster"
   port: 9999